// proto/helloworld.proto

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file proto/hello.proto (package helloworld, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HelloReply, HelloRequest } from "./hello_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service helloworld.Greeter
 */
export const Greeter = {
  typeName: "helloworld.Greeter",
  methods: {
    /**
     * @generated from rpc helloworld.Greeter.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: HelloRequest,
      O: HelloReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

