# use command:
# kubectl apply -f kubernetes/infisical/infisical-auth-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
  namespace: your-namespace
type: Opaque
stringData:
  clientId: "your_infisical_client_id"
  clientSecret: "your_infisical_client_secret"
