FROM node:22.4.1

WORKDIR /app

RUN npm install -g pnpm

# Copy the monorepo root's dependency manifests
COPY . .

# Install workspace dependencies
RUN pnpm install


# Dev command
CMD ["pnpm", "run", "--filter", "@apps/ts-grpc-demo", "start:dev"]