{{- if and .Values.containers.secretsFrom .Values.infisical }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.app }}-infisical-secret
  namespace: {{ .Release.Namespace }}
spec:
  hostAPI: http://infisical-backend.infisical.svc.cluster.local:8080/api

  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        envSlug: {{ .Values.infisical.envSlug | required "infisical.envSlug is required" }}
        projectId: {{ .Values.infisical.projectId | required "infisical.projectId is required" | quote }}
        secretsPath: /

  managedSecretReference:
    secretName: {{ .Values.containers.secretsFrom }}
    secretNamespace: {{ .Release.Namespace }}
    secretType: Opaque

  resyncInterval: {{ .Values.infisical.resyncInterval | default 60 }}
{{- end }}